### ISSUE TITLE
Add instructions for nvim-cmp

### ISSUE THREAD

**Issue by tzachar** [codota/tabnine-vim#94] opened 2021-09-08 17:50 UTC
Please add [cmp-tabnine](http://github.com/tzachar/cmp-tabnine) to the supported plugin instructions section.
10x

gz#6209

**Comment by bilucodota** [comment] 2021-09-08 18:15
Thanks for supporting the community! 
Closing as duplicate of https://github.com/codota/tabnine-vim/issues/93

**Closed by bilucodota** 2021-09-08 18:15 UTC
