### ISSUE TITLE
get error message when press :<c-f> in vim

### ISSUE THREAD

**Issue by Lgggg** [codota/tabnine-vim#60] opened 2020-04-18 12:16 UTC
I press : for commmand mode and then I press <c-f> for editting the command line in vim mode, but  i got err message like this:

**Comment by shaiahr** [comment] 2020-04-20 06:03
This is a duplicate of:
https://github.com/codota/tabnine-vim/issues/61

**Closed by shaiahr** 2020-04-20 06:03 UTC
Labels: duplicate
